version: '3.7'

services:
  # This runs the database that everything else connects to
  db:
    image: postgres:13
    ports:
      - 9001:5432
    environment:
      POSTGRES_USER: m-nny
      POSTGRES_PASSWORD: 'change-in-production'
      POSTGRES_DB: scrapper
    volumes:
      - db-volume:/var/lib/postgresql/data
  redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.microservice
      args:
        microservice: server
    env_file: .env.common
    ports: 
      - 3001:3001
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.microservice
      args:
        microservice: worker
    env_file: .env.common
  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile.microservice
      args:
        microservice: queue
    env_file: .env.common
    ports: 
      - 3002:3002

volumes:
  # Postgres' data
  db-volume:
